spring.application.name=routeapp
app.startup.demo-enabled=true
app.route-card.min-places=2
app.route-card.max-places=3
spring.datasource.url=jdbc:postgresql://localhost:5432/routeapp
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


